title: H! I am Pablo Castillo
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "pmcastillo79.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Pablo Castillo # add your name
author-img: pablo.jpg # add your photo
about-author: Backend Developer, Agile practitioner. Scrum Master # add description
social-twitter: pmcastillo79 # add your Twitter handle
social-facebook: p4blo79 # add your Facebook handle
social-github: pmcastillo79 # add your Github handle
social-linkedin: pmcastillo79 # add your Linkedin handle
social-email: pmcastillo79@gmail.com # add your Email address

# Disqus
discus-identifier: disqus_qKjX9iQ3w5 # add your discus identifier

# Tracker
analytics: UA-51514263-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]


